global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - /etc/prometheus/rules/*.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: demo-services
    static_configs:
      - targets: ["chaos-svc:8080"]
        labels: { service: demo-chaos-svc }
      - targets: ["podinfo-a:9898"]
        labels: { service: podinfo-a }
      - targets: ["podinfo-b:9898"]
        labels: { service: podinfo-b }
